# Copyright (c) 2026 Bob Hablutzel. All rights reserved.
#
# Licensed under a dual-license model: freely available for non-commercial use;
# commercial use requires a separate license. See LICENSE file for details.
# Contact license@geastalt.com for commercial licensing.

{{- range .Values.regions }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: lockmgr-mtls
  namespace: {{ .namespace }}
  labels:
    {{- include "lockmgr-istio.labels" $ | nindent 4 }}
spec:
  mtls:
    mode: {{ $.Values.peerAuthentication.mtls.mode }}
{{- end }}
