apiVersion: v2
name: contact-consumer-ids
description: Kafka consumer for processing Generate External Identifiers pending actions
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - contact
  - kafka
  - consumer
maintainers:
  - name: Geastalt
