# Copyright (c) 2026 Bob Hablutzel. All rights reserved.
#
# Licensed under a dual-license model: freely available for non-commercial use;
# commercial use requires a separate license. See LICENSE file for details.
# Contact license@geastalt.com for commercial licensing.

apiVersion: v2
name: lockmgr-istio
description: Istio service mesh configuration for distributed lock manager
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://freesvg.org/img/padlock.png
keywords:
  - istio
  - service-mesh
  - mtls
  - grpc
maintainers:
  - name: Geastalt
