# Copyright (c) 2026 Bob Hablutzel. All rights reserved.
#
# Licensed under a dual-license model: freely available for non-commercial use;
# commercial use requires a separate license. See LICENSE file for details.
# Contact license@geastalt.com for commercial licensing.

apiVersion: v2
name: contact-api
description: Contact API gRPC Service
type: application
version: 0.1.0
appVersion: "0.0.1-SNAPSHOT"
keywords:
  - contact
  - grpc
  - rest-api
maintainers:
  - name: Geastalt
