apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: address-mtls
  namespace: {{ .Values.service.namespace }}
  labels:
    {{- include "address-istio.labels" . | nindent 4 }}
spec:
  mtls:
    mode: {{ .Values.peerAuthentication.mtls.mode }}
